package entities;
// Generated Oct 31, 2022, 3:09:21 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoiceId generated by hbm2java
 */
@Embeddable
public class InvoiceId implements java.io.Serializable {

	private String invoiceId;
	private Long userId;
	private String email;
	private String tel;
	private String address;
	private byte statusId;
	private Date addedDate;

	public InvoiceId() {
	}

	public InvoiceId(String invoiceId, String email, String tel, String address, byte statusId, Date addedDate) {
		this.invoiceId = invoiceId;
		this.email = email;
		this.tel = tel;
		this.address = address;
		this.statusId = statusId;
		this.addedDate = addedDate;
	}

	public InvoiceId(String invoiceId, Long userId, String email, String tel, String address, byte statusId,
			Date addedDate) {
		this.invoiceId = invoiceId;
		this.userId = userId;
		this.email = email;
		this.tel = tel;
		this.address = address;
		this.statusId = statusId;
		this.addedDate = addedDate;
	}

	@Column(name = "InvoiceId", nullable = false, length = 32)
	public String getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "Email", nullable = false, length = 64)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Tel", nullable = false, length = 16)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "Address", nullable = false, length = 128)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "StatusId", nullable = false)
	public byte getStatusId() {
		return this.statusId;
	}

	public void setStatusId(byte statusId) {
		this.statusId = statusId;
	}

	@Column(name = "AddedDate", nullable = false, length = 19)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceId))
			return false;
		InvoiceId castOther = (InvoiceId) other;

		return ((this.getInvoiceId() == castOther.getInvoiceId()) || (this.getInvoiceId() != null
				&& castOther.getInvoiceId() != null && this.getInvoiceId().equals(castOther.getInvoiceId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getTel() == castOther.getTel()) || (this.getTel() != null && castOther.getTel() != null
						&& this.getTel().equals(castOther.getTel())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& (this.getStatusId() == castOther.getStatusId())
				&& ((this.getAddedDate() == castOther.getAddedDate()) || (this.getAddedDate() != null
						&& castOther.getAddedDate() != null && this.getAddedDate().equals(castOther.getAddedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInvoiceId() == null ? 0 : this.getInvoiceId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getTel() == null ? 0 : this.getTel().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + this.getStatusId();
		result = 37 * result + (getAddedDate() == null ? 0 : this.getAddedDate().hashCode());
		return result;
	}

}
