package entities;
// Generated Oct 31, 2022, 8:22:59 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoicedetailId generated by hbm2java
 */
@Embeddable
public class InvoicedetailId implements java.io.Serializable {

	private String invoiceId;
	private int productId;
	private short quantity;
	private int price;

	public InvoicedetailId() {
	}

	public InvoicedetailId(String invoiceId, int productId, short quantity, int price) {
		this.invoiceId = invoiceId;
		this.productId = productId;
		this.quantity = quantity;
		this.price = price;
	}

	@Column(name = "InvoiceId", nullable = false, length = 32)
	public String getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "ProductId", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "Quantity", nullable = false)
	public short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(short quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoicedetailId))
			return false;
		InvoicedetailId castOther = (InvoicedetailId) other;

		return ((this.getInvoiceId() == castOther.getInvoiceId()) || (this.getInvoiceId() != null
				&& castOther.getInvoiceId() != null && this.getInvoiceId().equals(castOther.getInvoiceId())))
				&& (this.getProductId() == castOther.getProductId()) && (this.getQuantity() == castOther.getQuantity())
				&& (this.getPrice() == castOther.getPrice());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInvoiceId() == null ? 0 : this.getInvoiceId().hashCode());
		result = 37 * result + this.getProductId();
		result = 37 * result + this.getQuantity();
		result = 37 * result + this.getPrice();
		return result;
	}

}
