package entities;
// Generated Oct 31, 2022, 8:22:59 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Publisher generated by hbm2java
 */
@Entity
@Table(name = "publisher", catalog = "minishop")
public class Publisher implements java.io.Serializable {

	private Integer publisherId;
	private String publisherName;

	public Publisher() {
	}

	public Publisher(String publisherName) {
		this.publisherName = publisherName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PublisherId", unique = true, nullable = false)
	public Integer getPublisherId() {
		return this.publisherId;
	}

	public void setPublisherId(Integer publisherId) {
		this.publisherId = publisherId;
	}

	@Column(name = "PublisherName", nullable = false, length = 128)
	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

}
